# Install the Twilio CLI and the serverless plugin then deploy the function
name: 'deploy-twilio'
description: 'Install the Twilio CLI and the serverless plugin then deploy the function'
runs:
  using: "composite"
  steps:
    - run: npm install twilio-cli -g && twilio plugins:install @twilio-labs/plugin-serverless && twilio serverless:deploy --runtime=node12 --service-name=serverless --environment=dev --force
      shell: bash
    - run: twilio serverless:deploy --runtime=node12 --service-name=serverless --environment=production --force
      shell: bash