# Prepare everything to compile the serverless application
name: 'compile-serverless'
description: 'Compile Serverless'
inputs:
  workspace-sid:  
    description: 'Twilio Workspace SID'
    required: true
  transfer-workflow-sid:  
    description: 'Chat Transfer Workflow SID'
    required: true
  sync-service-api-key:  
    description: 'Sync Service API Key'
    required: true
  sync-service-api-secret:  
    description: 'Sync Service API Secret'
    required: true
  sync-service-sid:
    description: 'Sync Service SID'
    required: true
  chat-service-sid:
    description: 'Chat Service SID'
    required: true
  operating-info-key:
    description: 'Operating Info Key'
    required: true      
runs:
  using: "composite"
  steps:
    - run: touch .env
      shell: bash
    - run: |
          cat <<EOT >> .env
          TWILIO_WORKSPACE_SID=${{ inputs.workspace-sid }}
          TWILIO_CHAT_TRANSFER_WORKFLOW_SID=${{ inputs.transfer-workflow-sid }}
          SYNC_SERVICE_API_KEY=${{ inputs.sync-service-api-key }}
          SYNC_SERVICE_API_SECRET=${{ inputs.sync-service-api-secret }}
          SYNC_SERVICE_SID=${{ inputs.sync-service-sid }}
          CHAT_SERVICE_SID=${{ inputs.chat-service-sid }}
          OPERATING_INFO_KEY=${{ inputs.operating-info-key }}
          EOT 
      shell: bash
    - run: npm ci
      shell: bash
    - run: npx tsc
      shell: bash